### ISSUE TITLE
Release packages for py27, py 33, py34

### ISSUE THREAD

**Issue by prat0318** [Yelp/swagger_spec_validator#10]
Needed other versions to support `pyramid_swagger` respective versions.

1) Make code compatible to py3
2) Release all versions to pypi.

**Comment by dnephin** [comment]
I just started trying out py3 support, I think I'm close to getting it working

**Comment by prat0318** [comment]
:heart:

**Comment by dnephin** [comment]
There are a couple issues with jsonschema being flaky on py3.  @striglia mentioned that he saw the same issues with pyramid_swagger.  If I can fix the other failures, I'll have to try and create a reproduction so we can ticket it on jsonschema.

**Comment by striglia** [comment]
A baby reproduction would be great. I noticed it had to do with ref resolving, possibly related to me using a custom RefResolver when I called the validator. Not sure if it's a Draft3, Draft4, or both issue.
