### ISSUE TITLE
why isn't it possible to validate a string?

### ISSUE THREAD

**Issue by ysangkok** [Yelp/swagger_spec_validator#19]
or any local file for that matter? thanks in advance.

**Comment by dnephin** [comment]
You can validate a local file, it's just not well document, Use `file://` urls, or pass the spec to https://github.com/Yelp/swagger_spec_validator/blob/v1.0.8/swagger_spec_validator/validator20.py#L27

**Comment by ysangkok** [comment]
it would still be very useful if i could pass a string instead of having to write it to disk first...

**Comment by palfrey** [comment]
You can do this.

```
from swagger_spec_validator.util import get_validator

spec_json = get_swagger()
validator = get_validator(spec_json)
validator.validate_spec(spec_json)
```

where `get_swagger` is a method for acquiring the string and JSON-parsing it

**Comment by ysangkok** [comment]
Closing since I stopped using this project.
