### ISSUE TITLE
spec validator does not catch when model id is different than the model name

### ISSUE THREAD

**Issue by kentwills** [Yelp/swagger_spec_validator#27]
@dnephin Swagger will raise an exception when a model id does not match its name, [here](https://github.com/digium/swagger-py/blob/master/swaggerpy/swagger_model.py#L60), however, the spec validator succeeds.

```
"models": {
    "mymodel": {
        "id": "mysupermodel"
}
```
results in:

```SwaggerError: (u"Model id doesn't match name")```

but passes the spec validator.

**Comment by prat0318** [comment]
`swagger_spec_validator` (ssv) uses jsonschema to validate the spec and inherently has some limitations to the validations. Rest of the validations are added additionaly as rich validations to ssv.

The `mode_id` part is removed now in Swagger 2.0 spec version and thus this was not added to the rich validations of swagger_spec_validator.
