### ISSUE TITLE
need to release new swagger_spec_validator to fix 'file' definition bug

### ISSUE THREAD

**Issue by ejbatutis** [Yelp/swagger_spec_validator#50]
The latest swagger_spec_validator release (2.0.2) does not have the updated schema.json that fixes this:

https://github.com/OAI/OpenAPI-Specification/issues/260

See:

https://github.com/OAI/OpenAPI-Specification/tree/master/schemas/v2.0

**Comment by dimbleby** [comment]
Yes please!

Are you able tell us if / when you next expect to make a release?

**Comment by ksharenkov** [comment]
I can create pull request with file replacement. Can it help?

**Comment by sjaensch** [comment]
Sure please do so!

**Comment by ksharenkov** [comment]
Seems I've detected problem. (during merge creation)
File [https://github.com/Yelp/swagger_spec_validator/blob/master/swagger_spec_validator/schemas/v2.0/schema.json]
already has a fix problem with file 
```
        "schema": {
          "oneOf": [
            {
              "$ref": "#/definitions/schema"
            },
            {
              "$ref": "#/definitions/fileSchema"
            }
          ]
        },
```
But the package on PyPI [https://pypi.python.org/pypi/swagger-spec-validator]
has the old variant of schema.json in package at swagger_spec_validator-2.0.2/swagger_spec_validator/schemas/v2.0/
```
        "schema": {
          "$ref": "#/definitions/schema"
        },
```
Looks like package on pypi.python.org need to be updated.

**Comment by burnes** [comment]
+1 for pypi release

**Comment by cadesalaberry** [comment]
I would love it as well !

For now, I am using the following in case it is of use to anyone:

    pip3 install https://github.com/Yelp/swagger_spec_validator/archive/master.zip --upgrade

**Comment by macisamuele** [comment]
#67 fixed the issue. Currently [version 2.0.4](https://pypi.python.org/pypi/swagger-spec-validator/2.0.4) is released on the public pypi ([``swagger-spec-validator-2.0.4.tar.gz``](https://pypi.python.org/packages/f1/45/f0d42353cafc5da7ea61e8de36cc159dc6e7a1a14437e4c904af2f790730/swagger-spec-validator-2.0.4.tar.gz#md5=3f0a6c46d7053f4ae0ce2238a24333a3)).
