### ISSUE TITLE
Validator is not checking is "items" key is present for "array" data types

### ISSUE THREAD

**Issue by AlstonLin** [Yelp/swagger_spec_validator#84]
For example this will pass the validator
```
...
foo:
    type: array
...
```
However, this should fail according to the [swagger specification](https://swagger.io/docs/specification/data-models/data-types/#array) as `items` is a required key for any `array` types

**Comment by bplotnick** [comment]
@macisamuele I think this was duped by #94 and fixed in #95, right?

**Comment by macisamuele** [comment]
@bplotnick you are correct.
Closing this as duplicate of #94
