### ISSUE TITLE
Multiple old versions at pypi.python.org

### ISSUE THREAD

**Issue by pbasista** [Yelp/swagger_spec_validator#89]
There are multiple versions of this library at https://pypi.python.org/pypi :

* https://pypi.python.org/pypi/swagger-spec-validator
* https://pypi.python.org/pypi/swagger-spec-validator3

Both contain almost the same, old version of the code, namely this one:
https://github.com/Yelp/swagger_spec_validator/tree/v2.1.0

I am not sure whether it is intentional, but it seems like a mistake. I would assume that there should be a newer version available somewhere, which would be similar to the current master branch.

**Comment by sdementen** [comment]
Shouldn't this issue be closed?

**Comment by pbasista** [comment]
I have just checked pypi and `swagger-spec-validator` is up to date with the releases of this repository. So, yes, I believe that this issue can now be closed.

`swagger-spec-validator3` still seems to be outdated, so if possible, I would remove it to avoid users' confusion.
